name: wildfire-dl
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - torchvision
  - cpuonly
  - pytorch
  - xarray
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - regionmask
  - ipython
  - plac
  - pytorch-lightning
  - pip
  - pip:
    - wandb

